# GET PRODUCTS
GET http://localhost:5000/api/products



# DELETE PRODUCT (replace 123 with actual product ID)
DELETE http://localhost:5000/api/products/123

# UPDATE PRODUCT (replace 123 with actual product ID)
PUT http://localhost:5000/api/products/123

# CREATE PRODUCT
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Pixel 8 pro",
  "price": 1099.99,
  "image": "https://example.com/image.jpg"
}